name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: What would you like?
      description: A clear description of the feature.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Why?
      description: What problem does this solve or what workflow does it improve?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workarounds or alternative approaches you've thought about.
